version: "3.9"
services:
  app-tail:
    build:
      context: ./app-tail # use the dockerfile in that directory.
    ports:
      - "3001:3001"
  app-head:
    build:
      context: ./app-head # use the dockerfile in that directory.
    ports:
      - "3000:3000"

